### ISSUE TITLE
Format and MimeType issue

### ISSUE THREAD

**Issue by dwong2006** [dbmdz/iiif-apis#2]
Hi,
According to http://iiif.io/api/presentation/2.1/#image-resources, "format" for the image resource should be something like "image/jpeg", however, it is currently printing out MimeType in its entirety:

"format": {"primaryType": "image","subType": "jpeg","extensions": ["jpg","jpeg","jpe"],"typeName": "image/jpeg"}

Would it still be compliant if it prints more than just the value of "typeName"?

**Comment by jbaiter** [comment]
Thank you for catching that, that is a pretty egregious bug (and it's definitely not compliant with the spec). I'm a bit shocked that the tests didn't catch that
Goes to show that line-coverage isn't everything.... Will be fixed asap!

**Comment by jbaiter** [comment]
Hm, there *is* a test for that and it passes.

**Question:** Are you using the [`IiifObjectMapper`](https://github.com/dbmdz/iiif-apis/blob/master/src/main/java/de/digitalcollections/iiif/model/jackson/IiifObjectMapper.java) class? Or are you using a custom `ObjectMapper` and just load the [`IiifModule`](https://github.com/dbmdz/iiif-apis/blob/master/src/main/java/de/digitalcollections/iiif/model/jackson/IiifModule.java)? If it's the latter, you absolutely have to copy the configuration and version check from the `IiifObjectMapper` to get valid JSON manifests.

**Comment by morpheus-87** [comment]
@dwong2006: does described problem still occur? Or can the issue be closed?
